### ISSUE TITLE
Eye_service doesn't seem to work correctly in Chef

### ISSUE THREAD

**Issue by hntd187** [hamann/eye-chef-cookbook#5]
I've tried for the life of me to get this working and I am absolutely stumped. Here is my stack trace, no matter what I try I get the same error and I don't seem to get a lot debugging.

```
 * eye_service[discover] action reload[2014-08-04T21:06:49+00:00] INFO: Processing eye_service[discover] action reload (neuron-discover::default line 73)


           ================================================================================
           Error executing action `reload` on resource 'eye_service[discover]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /opt/rbenv/shims/eye load /etc/eye/root/discover.eye ----
           STDOUT: 
           STDERR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:138:in `[]=': can't convert Proc into String (TypeError)

        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:138:in `block in set_environment'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:137:in `each'

        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:137:in `set_environment'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:315:in `block in fork_subprocess'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:300:in `fork'

        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:300:in `fork_subprocess'

            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:52:in `run_command'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout.rb:227:in `run_command'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/mixin/shell_out.rb:37:in `shell_out'
            from /tmp/kitchen/cookbooks/eye/providers/service.rb:141:in `run_command'
            from /tmp/kitchen/cookbooks/eye/providers/service.rb:65:in `block in class_from_file'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/lwrp_base.rb:138:in `block in action'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider.rb:125:in `run_action'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource.rb:648:in `run_action'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:49:in `run_action'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `block (2 levels) in converge'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `each'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `block in converge'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection.rb:96:in `execute_each_resource'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:80:in `converge'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:345:in `converge'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:431:in `do_run'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:213:in `block in run'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:207:in `fork'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:207:in `run'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:237:in `run_chef_client'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:226:in `block in run_application'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:218:in `loop'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:218:in `run_application'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:55:in `run'
            from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/bin/chef-solo:25:in `<top (required)>'

        from /usr/bin/chef-solo:23:in `load'
            from /usr/bin/chef-solo:23:in `<main>'
           ---- End output of /opt/rbenv/shims/eye load /etc/eye/root/discover.eye ----
           Ran /opt/rbenv/shims/eye load /etc/eye/root/discover.eye returned 1


       Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/eye/providers/service.rb:142:in `run_command'
           /tmp/kitchen/cookbooks/eye/providers/service.rb:65:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/neuron-discover/recipes/default.rb

            73: eye_service 'discover' do
            74:     action [:reload]

            75:     user_srv_uid "0"

        76:     user_srv_gid "0"
            77: end
            78: 



           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/neuron-discover/recipes/default.rb:73:in `from_file'

           eye_service("discover") do
             action [:reload]
             retries 0
             retry_delay 2
             guard_interpreter :default
             cookbook_name :"neuron-discover"
             recipe_name "default"

         user_srv_uid "0"
             user_srv_gid "0"

         service_name "discover"
           end


       [2014-08-04T21:06:49+00:00] INFO: Running queued delayed notifications before re-raising exception

       Running handlers:
       [2014-08-04T21:06:49+00:00] ERROR: Running exception handlers
       Running handlers complete

       [2014-08-04T21:06:49+00:00] ERROR: Exception handlers complete
       [2014-08-04T21:06:49+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 10 resources updated in 9.105261105 seconds
       [2014-08-04T21:06:49+00:00] ERROR: eye_service[discover] (neuron-discover::default line 73) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /opt/rbenv/shims/eye load /etc/eye/root/discover.eye ----
       STDOUT: 
       STDERR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:138:in `[]=': can't convert Proc into String (TypeError)
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:138:in `block in set_environment'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:137:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:137:in `set_environment'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:315:in `block in fork_subprocess'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:300:in `fork'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:300:in `fork_subprocess'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout/unix.rb:52:in `run_command'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout.rb:227:in `run_command'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/mixin/shell_out.rb:37:in `shell_out'
        from /tmp/kitchen/cookbooks/eye/providers/service.rb:141:in `run_command'
        from /tmp/kitchen/cookbooks/eye/providers/service.rb:65:in `block in class_from_file'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider/lwrp_base.rb:138:in `block in action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/provider.rb:125:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource.rb:648:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:49:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `block (2 levels) in converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:81:in `block in converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/resource_collection.rb:96:in `execute_each_resource'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/runner.rb:80:in `converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:345:in `converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:431:in `do_run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:213:in `block in run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.rb:207:in `fork'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/client.
       rb:207:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:237:in `run_chef_client'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:226:in `block in run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:218:in `loop'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application/solo.rb:218:in `run_application'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/application.rb:55:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/bin/chef-solo:25:in `<top (required)>'
        from /usr/bin/chef-solo:23:in `load'
        from /usr/bin/chef-solo:23:in `<main>'
       ---- End output of /opt/rbenv/shims/eye load /etc/eye/root/discover.eye ----
       Ran /opt/rbenv/shims/eye load /etc/eye/root/discover.eye returned 1
       [2014-08-04T21:06:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Any idea if this is a bug? I am using the newest chef-client that was just released 11.14.2

**Comment by hamann** [comment]
```
 user_srv_uid "0"
 user_srv_gid "0"
```

Did you try to set "root" instead of "0"? Maybe uid/gid is misleading, but names are expected here

**Comment by hntd187** [comment]
@hamann Nope, same error as before even with root instead of the 0s, what else can I provide to help debug this? I've also ran this a million times without these 2 attributes.

**Comment by hamann** [comment]
@hntd187 

```
$ cat /etc/eye/root/discover.eye
```

or try to load it manually as root with

```
$ /opt/rbenv/shims/eye load /etc/eye/root/discover.eye
```

Seems like your .eye configuration/template is invalid and eye can't handle it

**Comment by hntd187** [comment]
@hamann I'm rerunning the test-kitchen to get that for you right now, but I should note that the exact same commands work fine on the command line themselves ran either as sudo or as root directly. It's only when ran through chef do they error out.

**Comment by hamann** [comment]
Which version of this cookbook are you running? Could you try 0.6.1? Maybe it has something to do with the changes I released today

**Comment by hntd187** [comment]
Tried with various combinations of eye and eye-http versions to no avail. 

```
require 'eye-http'

def thin(proxy, port)
    name = "thin.#{port}"
    opts = ["-l log/development-thin.log", "-p #{port}", "-P /opt/neuronui/tmp/pids/#{name}.pid", "-d", "-t 60", "-e development", "-c /opt/neuronui", "-a 127.0.0.1"]
    proxy.process(name) do
        pid_file "/opt/neuronui/tmp/pids/#{name}.pid"
        start_command "#{BUNDLE} exec thin start #{opts * ' '}"
        stop_command "#{BUNDLE} exec thin stop #{opts * ' '}"
        restart_command "#{BUNDLE} exec thin restart #{opts * ' '}"
        stop_signals [:QUIT, 2.seconds, :TERM, 1.seconds, :KILL]
        stdall "thin.stdall.log"
    end
end

ENV['APP_HOST']=""
ENV['APP_ID']=""
ENV['APP_KEY']=""
ENV['AWS_SNS_ID']=""
ENV['AWS_SNS_KEY']=""
ENV['AWS_SNS_ARN']=""
RUBY    = 'ruby'
BUNDLE  = 'bundle'

Eye.config do
    http :enable => true, :host => "127.0.0.1", :port => 6666
    logger "/tmp/eye.log"
end

Eye.app 'thin-farm' do
    working_dir "/opt/neuronui"
    stop_on_delete true
    trigger :flapping, :times => 10, :within => 1.minute
    check :memory, :below => 5120.megabytes, :every => 30.seconds, :times => 5
    start_timeout 30.seconds
    group :web do
        chain :action => :restart, :grace => 5.seconds
        chain :action => :start, :grace => 0.2.seconds
        chain :action => :stop, :grace => 5.seconds
        0.upto(4) do |port|
            port = 3000+port
            thin self, port
        end
    end
end

```

Here is my discover.eye

**Comment by hamann** [comment]
Oook, I don't have much experience with rbenv, bundler and this load path mess.. but what happens if you do the following

```
$ shef -s
chef > include Chef::Mixin::ShellOut
chef > shell_out('/opt/rbenv/shims/eye load /etc/eye/root/discover.eye', :user => 'root', :group => 'root', :env => { 'HOME' => '/root' })
```

This should be the same command which will be executed by the provider and _should_ result in the same error.

How did you install chef? By the omnibus installer?

**Comment by hamann** [comment]
@hntd187 Nevermind.. I could reproduce it and I'm working on it...
